## Hands-on #1: elementwise operations

In [137]:
# Using lists
a = range(10)
b = range(2,12)
c = [0] * 10

# %timeit a + b # What does this do?
%timeit for i in range(10): c[i] = a[i] + b[i]
# from operator import add # you could do better, though
# %timeit map(add, a, b)
print(c)

# Using numpy arrays
import numpy as np
a = np.arange(10)
b = np.arange(2,12)
%timeit c = a + b
print(c)

100000 loops, best of 3: 3.86 µs per loop
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
The slowest run took 21.03 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 560 ns per loop
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [22]:
a.dot(b)

338250

In [24]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [25]:
2**a

array([ 1,  2,  4,  8, 16])

In [26]:
2**(3*a)-a

array([   1,    7,   62,  509, 4092])

## Hands-on #2: Exercise other operations

In [52]:
a = np.ones(10)
b = a + 0.001*np.random.random((10,))
print(np.may_share_memory(a, b))
print(np.allclose(a,b,rtol=0.01))

False
True


## Hands-on #3: Reductions

In [57]:
a = np.linspace(0.,10.,11)
a

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [62]:
a.sum(), a.prod(), a.max(), a.min(), a.mean(), a.argmin(), a.argmax()

(55.0, 0.0, 10.0, 0.0, 5.0, 0, 10)

In [56]:
print(a.sum())
print(a.cumsum())

55.0
[  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.]


## Hands-on #4: Shape manipulations

In [135]:
a = np.zeros((6,2))
b = np.reshape(a,(2,6),order='F')
print(np.may_share_memory(a, b))
b = np.reshape(a,(2,6))
print(np.may_share_memory(a, b))

False
True


In [124]:
a = np.zeros((2,3))
b = a.ravel()
c = a.flatten()
print(np.may_share_memory(a, b))
print(np.may_share_memory(a, c))

True
False


In [119]:
a = np.zeros((2,3))
print(a)
print(a.transpose())

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


## Hands-on #5: Sorting

In [66]:
a = np.random.random_integers(0,5,(3,))
a

array([4, 1, 2])

In [72]:
b = np.sort(a)
print("Sort : ",b)
print("Sort with fancy indexing",a[np.argsort(a)])
a.sort()
print("In place sort : ",a)


Sort :  [1 2 4]
Sort with fancy indexing [1 2 4]
In place sort :  [1 2 4]


In [77]:
a = np.array([1,3,2], dtype='int')
b = np.sort(a)
b

array([1, 2, 3])

In [78]:
a = np.array([1,3,2], dtype='float64')
b = np.sort(a)
b

array([ 1.,  2.,  3.])

In [91]:
np.random.shuffle(a)
a

array([ 1.,  3.,  2.])

In [114]:
a = np.random.random_integers(0,10,(3,4))
aorig = a.copy()
print(a)
b = np.ravel(a)
b.sort()
b = np.reshape(a,(3,4))
print(b)

[[ 6 10  6  4]
 [10  3  5  5]
 [ 3  2  6  7]]
[[ 2  3  3  4]
 [ 5  5  6  6]
 [ 6  7 10 10]]


In [118]:
a = aorig.copy()
print(a)
a.sort(axis=0)
a

[[ 6 10  6  4]
 [10  3  5  5]
 [ 3  2  6  7]]


array([[ 3,  2,  5,  4],
       [ 6,  3,  6,  5],
       [10, 10,  6,  7]])

In [111]:
a.sort(axis=1)
a

array([[ 2,  3,  4,  4],
       [ 4,  5,  5,  6],
       [ 7,  7,  9, 10]])